# Generated by Django 3.2 on 2021-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20210503_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentservices',
            name='contentThree',
            field=models.CharField(default='', max_length=100, verbose_name='Описание правого блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentservices',
            name='contentTwo',
            field=models.CharField(default='', max_length=100, verbose_name='Описание центрального блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentservices',
            name='nameThree',
            field=models.CharField(default='', max_length=21, verbose_name='Заголовок правого блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentservices',
            name='nameTwo',
            field=models.CharField(default='', max_length=21, verbose_name='Заголовок центрального блока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentservices',
            name='contentOne',
            field=models.CharField(max_length=100, verbose_name='Описание левого блока'),
        ),
        migrations.AlterField(
            model_name='contentservices',
            name='nameOne',
            field=models.CharField(max_length=21, verbose_name='Заголовок левого блока'),
        ),
    ]
