# Generated by Django 3.2 on 2021-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210503_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfooter',
            name='LinkFour',
            field=models.URLField(default='', verbose_name='Ссылка кнопки 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentfooter',
            name='LinkOne',
            field=models.URLField(default='', verbose_name='Ссылка кнопки 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentfooter',
            name='LinkThree',
            field=models.URLField(default='', verbose_name='Ссылка кнопки 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentfooter',
            name='LinkTwo',
            field=models.URLField(default='', verbose_name='Ссылка кнопки 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentfooter',
            name='incLinkFour',
            field=models.CharField(max_length=20, verbose_name='Класс иконки кнопки 4'),
        ),
        migrations.AlterField(
            model_name='contentfooter',
            name='incLinkOne',
            field=models.CharField(max_length=20, verbose_name='Класс иконки кнопки 1'),
        ),
        migrations.AlterField(
            model_name='contentfooter',
            name='incLinkThree',
            field=models.CharField(max_length=20, verbose_name='Класс иконки кнопки 3'),
        ),
        migrations.AlterField(
            model_name='contentfooter',
            name='incLinkTwo',
            field=models.CharField(max_length=20, verbose_name='Класс иконки кнопки 2'),
        ),
        migrations.AlterField(
            model_name='contentslidebar',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contentslidebar',
            name='position',
            field=models.CharField(blank=True, max_length=30, verbose_name='Должность'),
        ),
    ]
